<template>
  <div class="accounts">
      <div class="card" style="text-align: center; background-color: #343a40; color: white; padding: 20px; margin-top: 20px;">
        <h2 style="color:  #28a745;">4 Accounts...</h2>
        <!-- could include an imge of thinking here -->
        <!-- <div class="fakeimg" style="height:200px; background-color: #aaa; width: 100%; padding: 20px;">Image</div> -->
        <p>
          During his liftime Joseph smith gave 4 different accounts of his first vision. Each of these were directed to a different crowd and were given when he was at different stages of maturity in his life, and hence had different insights and perspectives. Below are all 4 of his accounts as well as the dates and context in which he gave them.
        </p>
      </div>

      <div class="card" style="background-color: #343a40; padding: 20px; margin-top: 20px; color: white;">
        <h2 style="color: #28a745;">FIRST ACCOUNT</h2>
        <hr style="height:1px; background-color: white;">
        <h5>Year: 1832</h5>
        <h5>Context:</h5>
        <p>The earliest known account of the First Vision, the only account written in Joseph Smith’s own hand, is found in a short, unpublished autobiography Joseph Smith produced in the second half of 1832. In the account, Joseph Smith described his consciousness of his own sins and his frustration at being unable to find a church that matched the one he had read about in the New Testament and that would lead him to redemption. He emphasized Jesus Christ’s Atonement and the personal redemption it offered. He wrote that “the Lord” appeared and forgave him of his sins. As a result of the vision, Joseph experienced joy and love, though, as he noted, he could find no one who believed his account.</p>
        <hr style="height:1px; background-color: white;">
        <h5>Account:</h5>
        <p>At about the age of twelve years, my mind became seriously impressed with regard to the all-important concerns for the welfare of my immortal soul, which led me to searching the scriptures—believing, as I was taught, that they contained the word of God and thus applying myself to them. My intimate acquaintance with those of different denominations led me to marvel exceedingly, for I discovered that they did not adorn their profession by a holy walk and godly conversation agreeable to what I found contained in that sacred depository. This was a grief to my soul.</p>
        <p>Thus, from the age of twelve years to fifteen I pondered many things in my heart concerning the situation of the world of mankind, the contentions and divisions, the wickedness and abominations, and the darkness which pervaded the minds of mankind. My mind became exceedingly distressed, for I became convicted of my sins, and by searching the scriptures I found that mankind did not come unto the Lord but that they had apostatized from the true and living faith, and there was no society or denomination that was built upon the gospel of Jesus Christ as recorded in the New Testament. I felt to mourn for my own sins and for the sins of the world, for I learned in the scriptures that God was the same yesterday, today, and forever, that he was no respecter of persons, for he was God.</p>
        <p>For I looked upon the sun, the glorious luminary of the earth, and also the moon, rolling in their majesty through the heavens, and also the stars shining in their courses, and the earth also upon which I stood, and the beasts of the ﬁeld, and the fowls of heaven, and the ﬁsh of the waters, and also man walking forth upon the face of the earth in majesty and in the strength of beauty, whose power and intelligence in governing the things which are so exceedingly great and marvelous, even in the likeness of him who created them. And when I considered upon these things, my heart exclaimed, “Well hath the wise man said, ‘It is a fool that saith in his heart, there is no God.’” My heart exclaimed, “All, all these bear testimony and bespeak an omnipotent and omnipresent power, a being who maketh laws and decreeth and bindeth all things in their bounds, who ﬁlleth eternity, who was and is and will be from all eternity to eternity.” And I considered all these things and that that being seeketh such to worship him as worship him in spirit and in truth.</p>
        <p>Therefore, I cried unto the Lord for mercy, for there was none else to whom I could go and obtain mercy. And the Lord heard my cry in the wilderness, and while in the attitude of calling upon the Lord, in the sixteenth year of my age, a pillar of light above the brightness of the sun at noonday came down from above and rested upon me. I was ﬁlled with the spirit of God, and the Lord opened the heavens upon me and I saw the Lord.</p>
        <p>And he spake unto me, saying, “Joseph, my son, thy sins are forgiven thee. Go thy way, walk in my statutes, and keep my commandments. Behold, I am the Lord of glory. I was crucified for the world, that all those who believe on my name may have eternal life. Behold, the world lieth in sin at this time, and none doeth good, no, not one. They have turned aside from the gospel and keep not my commandments. They draw near to me with their lips while their hearts are far from me. And mine anger is kindling against the inhabitants of the earth, to visit them according to their ungodliness and to bring to pass that which hath been spoken by the mouth of the prophets and apostles. Behold and lo, I come quickly, as it is written of me, in the cloud, clothed in the glory of my Father.”</p>
        <p>My soul was ﬁlled with love, and for many days I could rejoice with great joy. The Lord was with me, but I could ﬁnd none that would believe the heavenly vision. Nevertheless, I pondered these things in my heart.</p>
      </div>

      <div class="card" style="background-color: #343a40; padding: 20px; margin-top: 20px; color: white;">
        <h2 style="color: #28a745;">SECOND ACCOUNT</h2>
        <hr style="height:1px; background-color: white;">
        <h5>Year: 1835</h5>
        <h5>Context:</h5>
        <p>In the fall of 1835, Joseph Smith recounted his First Vision to Robert Matthews, a visitor to Kirtland, Ohio. The retelling, recorded in Joseph’s journal by his scribe Warren Parrish, emphasizes his attempt to discover which church was right, the opposition he felt as he prayed, and the appearance of one divine personage who was followed shortly by another. This account also notes the appearance of angels in the vision.</p>
        <hr style="height:1px; background-color: white;">
        <h5>Account:</h5>
        <p>Being wrought up in my mind respecting the subject of religion, and looking at the different systems taught the children of men, I knew not who was right or who was wrong. And considering it of the first importance that I should be right in matters that involve eternal consequences, being thus perplexed in mind I retired to the silent grove and bowed down before the Lord, under a realizing sense that he had said (if the Bible be true), “Ask, and you shall receive; knock, and it shall be opened; seek, and you shall find,” and again, “If any man lack wisdom, let him ask of God, who giveth to all men liberally, and upbraideth not.”</p>
        <p>Information was what I most desired at this time, and with a fixed determination to obtain it, I called upon the Lord for the first time in the place above stated. Or in other words, I made a fruitless attempt to pray; my tongue seemed to be swollen in my mouth, so that I could not utter. I heard a noise behind me, like some person walking towards me. I strove again to pray but could not. The noise of walking seemed to draw nearer. I sprung up on my feet and looked around but saw no person or thing that was calculated to produce the noise of walking.</p>
        <p>I kneeled again. My mouth was opened and my tongue liberated, and I called on the Lord in mighty prayer. A pillar of fire appeared above my head. It presently rested down upon me and filled me with joy unspeakable. A personage appeared in the midst of this pillar of flame, which was spread all around and yet nothing consumed. Another personage soon appeared, like unto the first. He said unto me, “Thy sins are forgiven thee.” He testified unto me that Jesus Christ is the son of God. And I saw many angels in this vision. I was about fourteen years old when I received this first communication.</p>
      </div>

      <div class="card" style="background-color: #343a40; padding: 20px; margin-top: 20px; color: white;">
        <h2 style="color: #28a745;">THIRD ACCOUNT</h2>
        <hr style="height:1px; background-color: white;">
        <h5>Year: 1838</h5>
        <h5>Context:</h5>
        <p>The narration of the First Vision best known to Latter-day Saints today is the 1838 account. First published in 1842 in the Times and Seasons, the Church’s newspaper in Nauvoo, Illinois, the account was part of a longer history dictated by Joseph Smith between periods of intense opposition. Whereas the 1832 account emphasizes the more personal story of Joseph Smith as a young man seeking forgiveness, the 1838 account focuses on the vision as the beginning of the “rise and progress of the Church.” Like the 1835 account, the central question of the narrative is which church is right.</p>
        <hr style="height:1px; background-color: white;">
        <h5>Account:</h5>
        <p>Some time in the second year after our removal to Manchester, there was in the place where we lived an unusual excitement on the subject of religion. It commenced with the Methodists, but soon became general among all the sects in that region of country. Indeed, the whole district of country seemed affected by it, and great multitudes united themselves to the different religious parties, which created no small stir and division amongst the people, some crying, “Lo, here!” and others, “Lo, there!” Some were contending for the Methodist faith, some for the Presbyterian, and some for the Baptist.</p>
        <p>For, notwithstanding the great love which the converts to these different faiths expressed at the time of their conversion, and the great zeal manifested by the respective clergy, who were active in getting up and promoting this extraordinary scene of religious feeling, in order to have everybody converted, as they were pleased to call it, let them join what sect they pleased; yet when the converts began to file off, some to one party and some to another, it was seen that the seemingly good feelings of both the priests and the converts were more pretended than real; for a scene of great confusion and bad feeling ensued—priest contending against priest, and convert against convert; so that all their good feelings one for another, if they ever had any, were entirely lost in a strife of words and a contest about opinions.</p>
        <p>I was at this time in my fifteenth year. My father’s family was proselyted to the Presbyterian faith, and four of them joined that church, namely, my mother, Lucy; my brothers Hyrum and Samuel Harrison; and my sister Sophronia.</p>
        <p>During this time of great excitement my mind was called up to serious reflection and great uneasiness; but though my feelings were deep and often poignant, still I kept myself aloof from all these parties, though I attended their several meetings as often as occasion would permit. In process of time my mind became somewhat partial to the Methodist sect, and I felt some desire to be united with them; but so great were the confusion and strife among the different denominations, that it was impossible for a person young as I was, and so unacquainted with men and things, to come to any certain conclusion who was right and who was wrong.</p>
        <p>My mind at times was greatly excited, the cry and tumult were so great and incessant. The Presbyterians were most decided against the Baptists and Methodists, and used all the powers of both reason and sophistry to prove their errors, or, at least, to make the people think they were in error. On the other hand, the Baptists and Methodists in their turn were equally zealous in endeavoring to establish their own tenets and disprove all others.</p>
        <p>In the midst of this war of words and tumult of opinions, I often said to myself: What is to be done? Who of all these parties are right; or, are they all wrong together? If any one of them be right, which is it, and how shall I know it?</p>
        <p>While I was laboring under the extreme difficulties caused by the contests of these parties of religionists, I was one day reading the Epistle of James, first chapter and fifth verse, which reads: If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him.</p>
        <p>Never did any passage of scripture come with more power to the heart of man than this did at this time to mine. It seemed to enter with great force into every feeling of my heart. I reflected on it again and again, knowing that if any person needed wisdom from God, I did; for how to act I did not know, and unless I could get more wisdom than I then had, I would never know; for the teachers of religion of the different sects understood the same passages of scripture so differently as to destroy all confidence in settling the question by an appeal to the Bible.</p>
        <p>At length I came to the conclusion that I must either remain in darkness and confusion, or else I must do as James directs, that is, ask of God. I at length came to the determination to “ask of God,” concluding that if he gave wisdom to them that lacked wisdom, and would give liberally, and not upbraid, I might venture.</p>
        <p>So, in accordance with this, my determination to ask of God, I retired to the woods to make the attempt. It was on the morning of a beautiful, clear day, early in the spring of eighteen hundred and twenty. It was the first time in my life that I had made such an attempt, for amidst all my anxieties I had never as yet made the attempt to pray vocally.</p>
        <p>After I had retired to the place where I had previously designed to go, having looked around me, and finding myself alone, I kneeled down and began to offer up the desires of my heart to God. I had scarcely done so, when immediately I was seized upon by some power which entirely overcame me, and had such an astonishing influence over me as to bind my tongue so that I could not speak. Thick darkness gathered around me, and it seemed to me for a time as if I were doomed to sudden destruction.</p>
        <p>But, exerting all my powers to call upon God to deliver me out of the power of this enemy which had seized upon me, and at the very moment when I was ready to sink into despair and abandon myself to destruction—not to an imaginary ruin, but to the power of some actual being from the unseen world, who had such marvelous power as I had never before felt in any being—just at this moment of great alarm, I saw a pillar of light exactly over my head, above the brightness of the sun, which descended gradually until it fell upon me.</p>
        <p>It no sooner appeared than I found myself delivered from the enemy which held me bound. When the light rested upon me I saw two Personages, whose brightness and glory defy all description, standing above me in the air. One of them spake unto me, calling me by name and said, pointing to the other—This is My Beloved Son. Hear Him!</p>
        <p>My object in going to inquire of the Lord was to know which of all the sects was right, that I might know which to join. No sooner, therefore, did I get possession of myself, so as to be able to speak, than I asked the Personages who stood above me in the light, which of all the sects was right (for at this time it had never entered into my heart that all were wrong)—and which I should join.</p>
        <p>I was answered that I must join none of them, for they were all wrong; and the Personage who addressed me said that all their creeds were an abomination in his sight; that those professors were all corrupt; that: “they draw near to me with their lips, but their hearts are far from me, they teach for doctrines the commandments of men, having a form of godliness, but they deny the power thereof.”</p>
        <p>20 He again forbade me to join with any of them; and many other things did he say unto me, which I cannot write at this time. When I came to myself again, I found myself lying on my back, looking up into heaven. When the light had departed, I had no strength; but soon recovering in some degree, I went home. And as I leaned up to the fireplace, mother inquired what the matter was. I replied, “Never mind, all is well—I am well enough off.” I then said to my mother, “I have learned for myself that Presbyterianism is not true.” It seems as though the adversary was aware, at a very early period of my life, that I was destined to prove a disturber and an annoyer of his kingdom; else why should the powers of darkness combine against me? Why the opposition and persecution that arose against me, almost in my infancy?</p>
      </div>

      <div class="card" style="background-color: #343a40; padding: 20px; margin-top: 20px; margin-bottom: 20px; color: white;">
        <h2 style="color: #28a745;">FOURTH ACCOUNT</h2>
        <hr style="height:1px; background-color: white;">
        <h5>Year: 1842</h5>
        <h5>Context:</h5>
        <p>Written in response to Chicago Democrat editor John Wentworth’s request for information about the Latter-day Saints, this account was printed in the Times and Seasons in 1842. (The “Wentworth letter,” as it is commonly known, is also the source for the Articles of Faith.)4 The account, intended for publication to an audience unfamiliar with Mormon beliefs, is concise and straightforward. As with earlier accounts, Joseph Smith noted the confusion he experienced and the appearance of two personages in answer to his prayer. The following year, Joseph Smith sent this account with minor modifications to a historian named Israel Daniel Rupp, who published it as a chapter in his book, He Pasa Ekklesia [The Whole Church]: An Original History of the Religious Denominations at Present Existing in the United States.</p>
        <hr style="height:1px; background-color: white;">
        <h5>Account:</h5>
        <p>When about fourteen years of age, I began to reflect upon the importance of being prepared for a future state, and upon enquiring about the plan of salvation, I found that there was a great clash in religious sentiment; if I went to one society, they referred me to one plan, and another to another, each one pointing to his own particular creed as the summum bonum of perfection. Considering that all could not be right, and that God could not be the author of so much confusion, I determined to investigate the subject more fully, believing that if God had a church it would not be split up into factions, and that if he taught one society to worship one way, and administer in one set of ordinances, he would not teach another principles which were diametrically opposed. Believing the word of God, I had confidence in the declaration of James: “If any man lack wisdom, let him ask of God, who giveth to all men liberally and upbraideth not, and it shall be given him.”
        </p>
        <p>I retired to a secret place in a grove and began to call upon the Lord. While fervently engaged in supplication, my mind was taken away from the objects with which I was surrounded, and I was enwrapped in a heavenly vision and saw two glorious personages who exactly resembled each other in features and likeness, surrounded with a brilliant light which eclipsed the sun at noonday. They told me that all religious denominations were believing in incorrect doctrines and that none of them was acknowledged of God as his church and kingdom. And I was expressly commanded to “go not after them,” at the same time receiving a promise that the fulness of the gospel should at some future time be made known unto me.</p>
      </div>
  </div>
</template>

<style>
h2 {
  font-size: 2em;
}

h5 {
  text-align: left;
  font-size: 1.5em;
}

p {
  text-align: left;
  font-size: 1.5em;
}

</style>
